default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: jackdouglas 
  password: password    

development:
  <<: *default
  database: rubygembootcamp_development 

test:
  <<: *default
  database: rubygembootcamp_test

